// GENERATED by tools/make_positions.py from the shield's .kicad_pcb -- do not edit by hand.
// Board frame: origin = UNO lower-left corner (jacks on the left), mm, seen from the top.

pcb_holes = [[13.97, 2.54], [66.04, 7.62], [66.04, 35.56]];  // shield M3 holes H1..H3
J1_pads = [[3.64, 18.94], [3.64, 15.44]];  // SIGNAL IN, wire entry faces -x
J3_pads = [[3.64, 27.74], [3.64, 24.24]];  // TRIG IN, wire entry faces -x
J2_pads = [[64.94, 14.54], [64.94, 18.04]];  // QPS OUT, wire entry faces +x
J4_pads = [[43.94, 14.54], [46.48, 14.54], [49.02, 14.54], [51.56, 14.54]];  // 1x4 socket PRE_OUT A2 VREF GND
U1_pads = [[15.94, 14.54], [18.48, 14.54], [21.02, 14.54], [23.56, 14.54], [26.1, 14.54], [28.64, 14.54], [31.18, 14.54], [33.72, 14.54], [36.26, 14.54], [38.8, 14.54]];  // ADS1115 1x10 socket
U2_pads = [[47.44, 35.54], [47.44, 33.0], [47.44, 30.46], [47.44, 27.92], [47.44, 25.38], [47.44, 22.84]];  // MCP4725 1x6 socket
J5_pos = [58.34, 43.54];  // SMA vertical centre pin
J1_crtyd = [-1.405, 13.145, 7.285, 21.235];  // courtyard [x0,y0,x1,y1]
J2_crtyd = [61.295, 12.245, 69.985, 20.335];  // courtyard [x0,y0,x1,y1]
J3_crtyd = [-1.405, 21.945, 7.285, 30.035];  // courtyard [x0,y0,x1,y1]
J5_crtyd = [54.125, 39.325, 62.555, 47.755];  // courtyard [x0,y0,x1,y1]
guard_bbox = [36.34, 38.84, 60.465, 48.14];  // guard top
usb_keepout = [0.0, 31.34, 10.54, 44.84];  // USB-B jack
icsp_keepout = [61.94, 23.94, 67.84, 32.14];  // ICSP header
dc_keepout = [0.0, 0.0, 11.94, 13.04];  // DC jack
ads_outline = [13.4, 12.51, 41.34, 29.78];  // ADS1115 board lying flat, 1.10 x 0.68 in
mcp_outline = [46.17, 21.57, 61.41, 36.81];  // MCP4725 board lying flat, 0.6 x 0.6 in
