#!/usr/bin/env python3
"""Turn build/pcb_dump.json (from tools/dump_pcb.py) into scad/pcb_positions.scad.

Frame used by the enclosure ("board frame", mm): origin at the UNO's lower-left corner
as seen from the top on the Arduino A000066 drawing (USB/DC jacks on the left edge,
power/analog header along y = 2.54, digital header along y = 50.8).
    x_board = x_kicad - 72.06        y_board = 102.54 - y_kicad
(the shield's Edge.Cuts is the UNO outline at KiCad x 72.06..140.64, y 49.60..102.54).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
X0, Y0 = 72.06, 102.54


def b(x, y):
    return round(x - X0, 3), round(Y0 - y, 3)


def main():
    d = json.load(open(os.path.join(ROOT, "build", "pcb_dump.json")))
    f = d["fps"]
    L = ["// GENERATED by tools/make_positions.py from the shield's .kicad_pcb -- do not edit by hand.",
         "// Board frame: origin = UNO lower-left corner (jacks on the left), mm, seen from the top.", ""]

    def pads(ref):
        return [b(p[1], p[2]) for p in f[ref]["pads"]]

    def v(name, val, note=""):
        L.append(f"{name} = {json.dumps(val)};" + (f"  // {note}" if note else ""))

    v("pcb_holes", [list(b(*f[h]["pos"])) for h in ("H1", "H2", "H3")], "shield M3 holes H1..H3")
    for ref, note in (("J1", "SIGNAL IN, wire entry faces -x"), ("J3", "TRIG IN, wire entry faces -x"),
                      ("J2", "QPS OUT, wire entry faces +x"), ("J4", "1x4 socket PRE_OUT A2 VREF GND"),
                      ("U1", "ADS1115 1x10 socket"), ("U2", "MCP4725 1x6 socket")):
        v(f"{ref}_pads", [list(p) for p in pads(ref)], note)
    v("J5_pos", list(b(*f["J5"]["pos"])), "SMA vertical centre pin")
    # courtyards -> body extents (courtyard minus the 0.5 mm courtyard margin... kept as-is, conservative)
    for ref in ("J1", "J2", "J3", "J5"):
        c = f[ref]["crtyd"]
        (xa, ya), (xb, yb) = b(c[0], c[1]), b(c[2], c[3])
        v(f"{ref}_crtyd", [min(xa, xb), min(ya, yb), max(xa, xb), max(ya, yb)], "courtyard [x0,y0,x1,y1]")
    for z in d["zones"]:
        key = {"guard top": "guard_bbox", "USB-B jack": "usb_keepout", "DC jack": "dc_keepout",
               "ICSP header": "icsp_keepout"}.get(z["name"])
        if key:
            c = z["bbox"]
            (xa, ya), (xb, yb) = b(c[0], c[1]), b(c[2], c[3])
            v(key, [min(xa, xb), min(ya, yb), max(xa, xb), max(ya, yb)], z["name"])
    # breakout outlines: from generate_pcb.py ADS_OUTLINE / MCP_OUTLINE (Uno coords + (27.94, 2.54))
    v("ads_outline", [13.40, 12.51, 41.34, 29.78], "ADS1115 board lying flat, 1.10 x 0.68 in")
    v("mcp_outline", [46.17, 21.57, 61.41, 36.81], "MCP4725 board lying flat, 0.6 x 0.6 in")
    out = os.path.join(ROOT, "scad", "pcb_positions.scad")
    open(out, "w").write("\n".join(L) + "\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
